# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amalgam < Formula
  desc ""
  homepage ""
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/manojkarthick/amalgam/releases/download/v0.1.5/amalgam-0.1.5-darwin-amd64.tar.gz"
      sha256 "aaa135515f3121e55d78d3a998cfbb3221a8076abfcb0b2c486e91792ce8c3af"

      def install
        bin.install "amalgam"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/manojkarthick/amalgam/releases/download/v0.1.5/amalgam-0.1.5-darwin-arm64.tar.gz"
      sha256 "83da2a466bf92c263ba2192e648d0e4258bea92a52dbc560fca6cc168ae77bfb"

      def install
        bin.install "amalgam"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/manojkarthick/amalgam/releases/download/v0.1.5/amalgam-0.1.5-linux-amd64.tar.gz"
      sha256 "9a8fdc24e9718cdfef9207a868ef10086e093a7c6fcb6dab4665b6aa5bc8bf62"

      def install
        bin.install "amalgam"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/manojkarthick/amalgam/releases/download/v0.1.5/amalgam-0.1.5-linux-arm64.tar.gz"
      sha256 "b3d359fe6ec53eb1cf7a69d9d5e6ea16182369fd9382e120daac0fe8e2d5d5a7"

      def install
        bin.install "amalgam"
      end
    end
  end
end
