# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amalgam < Formula
  desc "Build and upload macOS universal binaries from Github Releases"
  homepage "https://github.com/manojkarthick/amalgam"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/manojkarthick/amalgam/releases/download/v0.1.5/amalgam-0.1.5-darwin-arm64.tar.gz"
      sha256 "1104746195b24b53d6518e35f2a0caeb10b5da2eef16fb0b204edbc9f841c263"

      def install
        bin.install "amalgam"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/manojkarthick/amalgam/releases/download/v0.1.5/amalgam-0.1.5-darwin-amd64.tar.gz"
      sha256 "1d1f8abbcb063ed5c195cd8c82ad1b195420fcea5c32f735a6387d2e2fe24ec7"

      def install
        bin.install "amalgam"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/manojkarthick/amalgam/releases/download/v0.1.5/amalgam-0.1.5-linux-amd64.tar.gz"
      sha256 "c82ee9dd4fe66513fb0983c247bd071f0696387d8150f157e945aa52ccc83e88"

      def install
        bin.install "amalgam"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/manojkarthick/amalgam/releases/download/v0.1.5/amalgam-0.1.5-linux-arm64.tar.gz"
      sha256 "dbcea5a7c7cd466c79a7b28c6778ebb55830a26d28dc518bb6b6a508e3457c48"

      def install
        bin.install "amalgam"
      end
    end
  end
end
