# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codeartoken < Formula
  desc "Refresh AWS CodeArtifact credentials for Maven"
  homepage "https://github.com/manojkarthick/codeartoken"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/manojkarthick/codeartoken/releases/download/v0.1.1/codeartoken-0.1.1-darwin-arm64.tar.gz"
      sha256 "065e352c053e61ebeede98b5dc45b7fecf06ad8403b114a37317b00d343444ac"

      def install
        bin.install "codeartoken"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/manojkarthick/codeartoken/releases/download/v0.1.1/codeartoken-0.1.1-darwin-x64.tar.gz"
      sha256 "b283ca1e0f74c061d4e5563a140a003cb45aa04ed8aa0351e201993750290bf8"

      def install
        bin.install "codeartoken"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/manojkarthick/codeartoken/releases/download/v0.1.1/codeartoken-0.1.1-linux-arm64.tar.gz"
      sha256 "42099541ae8913f8b28a880f543951a5740c089635868dbafb97afd78d508fb5"

      def install
        bin.install "codeartoken"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/manojkarthick/codeartoken/releases/download/v0.1.1/codeartoken-0.1.1-linux-x64.tar.gz"
      sha256 "facfae6ce983c193bc2534dc13de7ad28ca402455605df0ee79ab9e24ce1f417"

      def install
        bin.install "codeartoken"
      end
    end
  end
end
