# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codeartoken < Formula
  desc ""
  homepage ""
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/manojkarthick/codeartoken/releases/download/v0.1.1/codeartoken-0.1.1-darwin-arm64.tar.gz"
      sha256 "032c7e333cc6d4b87adbb195a87b013a9b105cb345b3fbacb756b214124e28a8"

      def install
        bin.install "codeartoken"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/manojkarthick/codeartoken/releases/download/v0.1.1/codeartoken-0.1.1-darwin-x64.tar.gz"
      sha256 "3846aa982578beb8f20a35acfadcae18e3fc93d9b2a987888f6f078188753ef0"

      def install
        bin.install "codeartoken"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/manojkarthick/codeartoken/releases/download/v0.1.1/codeartoken-0.1.1-linux-arm64.tar.gz"
      sha256 "30d9093a4193cad3a0de7c49c4d93794026ffbefe0e1a31ae8e54e1af5bdc6c8"

      def install
        bin.install "codeartoken"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/manojkarthick/codeartoken/releases/download/v0.1.1/codeartoken-0.1.1-linux-x64.tar.gz"
      sha256 "0384af9d6968f041799017910ffd4eb14d1d50f197f2f0ed1c5ad1294ec336fe"

      def install
        bin.install "codeartoken"
      end
    end
  end
end
