# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubUploadAsset < Formula
  desc "Upload assets to Github Releases"
  homepage "https://github.com/manojkarthick/github-upload-asset"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/manojkarthick/github-upload-asset/releases/download/v0.1.2/github-upload-asset-0.1.2-darwin-x64.tar.gz"
      sha256 "72c84e93bb01eb327b2e1a755423f375c183183e03fc26f7ce8c515a326edc5d"

      def install
        bin.install "github-upload-asset"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/manojkarthick/github-upload-asset/releases/download/v0.1.2/github-upload-asset-0.1.2-darwin-arm64.tar.gz"
      sha256 "ca012a31d55683a00b73adc8433d06e92482a35d998417f3de83d8c4a623a591"

      def install
        bin.install "github-upload-asset"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/manojkarthick/github-upload-asset/releases/download/v0.1.2/github-upload-asset-0.1.2-linux-x64.tar.gz"
      sha256 "35ea9a25bd15eeb2523ee78e5b1872ef2267fc49ab2f072e99f1acfc23395513"

      def install
        bin.install "github-upload-asset"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/manojkarthick/github-upload-asset/releases/download/v0.1.2/github-upload-asset-0.1.2-linux-arm64.tar.gz"
      sha256 "3ac46a9b6703916cad346a4885bcc849f78dd7cb98eeeea11c85d904d1346856"

      def install
        bin.install "github-upload-asset"
      end
    end
  end
end
